### ISSUE TITLE
Parameterise database inputs

### ISSUE THREAD

**Issue by Alex-Yates** [Alex-Yates/PowerShell_GeneratePermissions#2]
Rather than hardcoding the database names, allow the user to provide a parameter of comma delimited database names and then geneate the code for each database in the string.

Perhaps there is a better way to do this? Can ps scripts accept an array of strings as a parameter. Need to check.

**Comment by paschott** [comment]
You should be able to accept an array of strings and then do a foreach loop to parse through them. I've done that in a couple of other scripts I've written (long after these scripts). Works for a single string or an array of them.

**Comment by Alex-Yates** [comment]
Thanks! I'll do that then! ;-P

**Comment by Alex-Yates** [comment]
Resolved with PR above
